version: "2"
services:
  app:
    command: ["node", "dist/server.js"]
    container_name: road_service_node
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mysql
  mysql:
    container_name: road_service_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./temp/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
