version: "2"
services:
  app:
    command: ["node", "dist/server.js"]
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
